steps:
  - id: test
    name: gradle:8.9-jdk17
    entrypoint: sh
    args:
      - -c
      - ./gradlew :releva-sdk:test
  - id: build
    name: gradle:8.9-jdk17
    entrypoint: sh
    args:
      - -c
      - ./gradlew :releva-sdk:build
  - id: assemble-release
    name: gradle:8.9-jdk17
    entrypoint: sh
    args:
      - -c
      - ./gradlew :releva-sdk:assembleRelease
  - id: configure-git
    name: gcr.io/cloud-builders/git
    args:
      - config
      - --global
      - user.email
      - cloudbuild@releva.ai
  - id: configure-git-name
    name: gcr.io/cloud-builders/git
    args:
      - config
      - --global
      - user.name
      - Releva Cloud Build
  - id: release
    name: ubuntu:22.04
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update -qq && apt-get install -y -qq make git openjdk-17-jdk-headless > /dev/null
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        make release
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
timeout: '2000s'
